### ISSUE TITLE
Doesnt install using pip.

### ISSUE THREAD

**Issue by devxpy** [nathan-hoad/python-iwlib#4]
In file included from iwlib/utils.c:17:0:
    iwlib/utils.h:2:19: fatal error: iwlib.h: No such file or directory
     #include <iwlib.h>
                       ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-m7bch8bt/iwlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k1x14wgz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-m7bch8bt/iwlib/

**Comment by nathan-hoad** [comment]
You need to install the wireless_tools package.

**Comment by devxpy** [comment]
Okay. Thanks. It works now.

**Comment by devxpy** [comment]
Okay, Thx. 
I had to do this on Ubutu 17, just for refrence
`sudo apt install libiw-dev`
