### ISSUE TITLE
tagged release

### ISSUE THREAD

**Issue by dvzrv** [nathan-hoad/python-iwlib#6]
Could you tag a new release?
I'd like to package 1.6.

**Comment by dvzrv** [comment]
@nathan-hoad [pypi also doesn't have 1.6](https://pypi.python.org/pypi/iwlib/).

**Comment by dvzrv** [comment]
As this is now in [community] on Arch Linux I'd like to know if I can still count on a release being made. iwlib is an optional depend for qtile.

**Comment by nathan-hoad** [comment]
Apologies for the delay - I was trying to organise moving halfway around the world for the first quarter of the year so I had to stop working on some things. I've released 1.6 and uploaded it.

**Comment by dvzrv** [comment]
thanks! (I'm used to some projects taking a little longer ;-) ).
hope you could settle in properly! All the best for the new home!
